# Generated by Django 5.1.3 on 2025-11-17 18:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='party.member'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='qty',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10),
        ),
    ]
